default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: familyrecipes_development

test:
  <<: *default
  database: familyrecipes_test

production:
  <<: *default
  database: familyrecipes_production
  username: <%= ENV["DATABASE_USERNAME"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
  host: <%= ENV.fetch("DATABASE_HOST", "localhost") %>
