default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000
  idle_timeout: 300
  pragmas:
    journal_mode: wal
    synchronous: normal
    mmap_size: 134217728
    cache_size: -64000

development:
  primary:
    <<: *default
    database: storage/development.sqlite3
  cable:
    <<: *default
    database: storage/development_cable.sqlite3
    migrations_paths: db/cable_migrate

test:
  primary:
    <<: *default
    database: storage/test.sqlite3
  cable:
    <<: *default
    database: storage/test_cable.sqlite3
    migrations_paths: db/cable_migrate

production:
  primary:
    <<: *default
    database: storage/production.sqlite3
  cable:
    <<: *default
    database: storage/production_cable.sqlite3
    migrations_paths: db/cable_migrate
