default: &default
  site_title: Biagini Family Recipes
  homepage_heading: Our Recipes
  homepage_subtitle: "A collection of our family's favorite recipes."
  github_url: https://github.com/chris-biagini/familyrecipes

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
